@startuml@startuml

skinparam classAttributeIconSize 0title Class diagram — OOP/DOAN project (generated)

hide empty members

package "code.kethua" {

' Packages  abstract class ConNguoi {

package code.doituong {    +Hoten : String

  class GiaoDich    +Diachi : String

  interface INhapXuat    +Sdt : long

    +Nhap(sc: Scanner)

  class HoaDon extends GiaoDich {    +Xuat()

    - MaHDB : String  }

    - dsct : DanhSachChitietHoaDon

    - dskh : DanhSachKhachHang  abstract class GiaoDich {

    - dsnv : DanhSachNhanVien    -ngayGD : Date

    + getMaHD() : String    -nv : NhanVien

    + getdsct() : DanhSachChitietHoaDon    -kh : KhachHang

    + Nhap(sc: Scanner) : void    +getNgayGD() : Date

    + Xuat() : void    +setNgayGD(Date)

    + Thanhtien() : double    +getNv() : NhanVien

  }    +setNv(NhanVien)

    +getKh() : KhachHang

  class ChiTietHoaDon implements INhapXuat {    +setKh(KhachHang)

    - hd : HoaDon    +Nhap(sc: Scanner)

    - sp : SanPham    +Xuat()

    - soluong : int    +Thanhtien() : double

    + Tinhtien() : double  }

    + Nhap(sc: Scanner) : void}

    + Xuat() : void

  }package "code.doituong" {

  interface INhapXuat

  class SanPham implements INhapXuat {

    + getMa() : String  class HoaDon {

    + getTen() : String    -MaHDB : String

    + getGia() : double    -dsct : code.danhsach.DanhSachChitietHoaDon

  }    -dskh : code.danhsach.DanhSachKhachHang

    -dsnv : code.danhsach.DanhSachNhanVien

  class Loai implements INhapXuat    -MaHDNext : int {static}

    +getMaHD() : String

  class ConNguoi    +setMaHD(String)

  class KhachHang extends ConNguoi    +getdsct() : code.danhsach.DanhSachChitietHoaDon

  class NhanVien extends ConNguoi    +Thanhtien() : double

  class NhanVienFullTime extends NhanVien    +Nhap(sc: Scanner)

  class NhanVienPartTime extends NhanVien    +Xuat()

  }

  class Kho {

    - sp : SanPham  class ChiTietHoaDon {

    - Dauvao : int    -hd : HoaDon

    - Daura : int    -sp : SanPham

    - Ton : int    -soluong : int

  }    -dshd : code.danhsach.DanhSachHoaDon

}    -dssp : code.danhsach.DanhSachSanPham

    +Tinhtien() : double

package code.danhsach {    +Nhap(sc: Scanner)

  class DanhSachHoaDon {    +Xuat()

    - dshd : HoaDon[]  }

    - n : int

    + ReadFile(dskh: DanhSachKhachHang, dsnv: DanhSachNhanVien) : void  class SanPham {

    + WriteFile() : void    -ma : String

    + Them(sc: Scanner, dskh: DanhSachKhachHang, dsnv: DanhSachNhanVien, dssp: DanhSachSanPham, dsct: DanhSachChitietHoaDon) : void    -ten : String

    + Timkiem_MaHD(ma: String) : HoaDon    -hang : String

  }    -loai : Loai

  class DanhSachChitietHoaDon {    -gia : double

    - dsct : ChiTietHoaDon[]    +getMa() : String

    - n : int    +getTen() : String

    + ReadFile(dshd: DanhSachHoaDon, dssp: DanhSachSanPham) : void    +getGia() : double

    + WriteFile() : void    +Nhap(sc: Scanner)

    + Them(sc: Scanner, dshd: DanhSachHoaDon, dssp: DanhSachSanPham) : void    +Xuat()

    + ThemChiTiet(ct: ChiTietHoaDon) : void    +tofile() : String

  }  }

  class DanhSachKhachHang { - dskh : KhachHang[] }

  class DanhSachNhanVien { - dsnv : NhanVien[] }  class Loai {

  class DanhSachSanPham { - dssp : SanPham[] }    -maLoai : String

  class DanhSachLoai { - dsloai : Loai[] }    -tenLoai : String

  class DanhSachKho { - dskho : Kho[] }    +getMaloai() : String

}    +getTenloai() : String

  }

' Relationships

HoaDon "1" o-- "*" ChiTietHoaDon : contains  class KhachHang {

ChiTietHoaDon --> HoaDon : hd    +MaKH : String

ChiTietHoaDon --> SanPham : sp    +Nhap(sc: Scanner)

SanPham --> Loai    +Xuat()

DanhSachHoaDon "1" *-- "*" HoaDon  }

DanhSachChitietHoaDon "1" *-- "*" ChiTietHoaDon

DanhSachKhachHang "1" *-- "*" KhachHang  class NhanVien {

DanhSachNhanVien "1" *-- "*" NhanVien    +MaNV : String

DanhSachSanPham "1" *-- "*" SanPham    +Chucvu : String

DanhSachLoai "1" *-- "*" Loai    +ChamCong : int

DanhSachKho "1" *-- "*" Kho    +Luong : long

HoaDon --> KhachHang : kh    +Nhap(sc: Scanner)

HoaDon --> NhanVien : nv    +Xuat()

Kho --> SanPham : sp  }

}

@enduml

package "code.danhsach" {
  class DanhSachHoaDon {
    -dshd : code.doituong.HoaDon[]
    -n : int
    +ReadFile(dskh, dsnv)
    +WriteFile()
    +Them(...)
  }

  class DanhSachChitietHoaDon {
    -dsct : code.doituong.ChiTietHoaDon[]
    -n : int
    +ReadFile(dshd, dssp)
    +WriteFile()
    +Them(sc, dshd, dssp)
    +ThemChiTiet(ct)
  }

  class DanhSachSanPham {
    -ds : code.doituong.SanPham[]
    -n : int
    +docFile(dsl)
    +ghiFile()
    +TimTheoMa(ma) : SanPham
  }

  class DanhSachKhachHang {
    -dskh : code.doituong.KhachHang[]
    -n : int
  }

  class DanhSachNhanVien {
    -dsnv : code.doituong.NhanVien[]
    -n : int
  }
}

' Relationships
HoaDon --|> GiaoDich
KhachHang --|> ConNguoi
NhanVien --|> ConNguoi

' Associations / aggregations
HoaDon "1" o-- "0..*" ChiTietHoaDon : contains
code.danhsach.DanhSachChitietHoaDon "1" *-- "0..*" ChiTietHoaDon
code.danhsach.DanhSachHoaDon "1" *-- "0..*" HoaDon
ChiTietHoaDon --> SanPham
GiaoDich --> KhachHang
GiaoDich --> NhanVien

' Interfaces
INhapXuat <|.. ConNguoi
INhapXuat <|.. SanPham
INhapXuat <|.. ChiTietHoaDon
INhapXuat <|.. Loai

@enduml
